apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackprac
  labels:
    app: hackprac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackprac
  template:
    metadata:
      labels:
        app: hackprac
    spec:
      imagePullSecrets:
      - name: acr-secret 
      containers:
      - name: hackprac-deployment-az
        image: elletamc.azurecr.io/hackprac:v1 
        ports:
        - name: http
          containerPort: 5000
