apiVersion: v1
kind: Service
metadata:
  name: hackprac-deployment-az
  labels:
    app: hackprac-deployment-az
spec:
  type: NodePort
  selector:
    app: hackprac-deployment-az
    env: prod
  ports:
  - port: 5000
    targetPort: http
    nodePort: 32410
    protocol: TCP    
    name: http